dataset_name: "wireframe"
add_augmentation_to_all_splits: False
gray_scale: True
# return_type: "paired_desc"
random_seed: 0
# Ground truth source (official or path to the epxorted h5 dataset.)
gt_source_train: "official"
gt_source_test: "official"
# Date preprocessing configuration.
preprocessing:
    resize: [512, 512]
    blur_size: 11
augmentation:
    random_scaling:
        enable: True
        range: [0.7, 1.5]
    photometric:
        enable: true
        primitives: ['random_brightness', 'random_contrast',
                     'additive_speckle_noise', 'additive_gaussian_noise',
                     'additive_shade', 'motion_blur' ]
        params:
            random_brightness: {brightness: 0.2}
            random_contrast: {contrast: [0.3, 1.5]}
            additive_gaussian_noise: {stddev_range: [0, 10]}
            additive_speckle_noise: {prob_range: [0, 0.0035]}
            additive_shade:
                transparency_range: [-0.5, 0.5]
                kernel_size_range: [100, 150]
            motion_blur: {max_kernel_size: 3}
        random_order: True
    homographic:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true
        valid_border_margin: 3
# The homography adaptation configuration
homography_adaptation:
    num_iter: 100
    aggregation: 'sum'
    mode: 'ver1'
    valid_border_margin: 3
    min_counts: 30
    homographies:
        translation: true
        rotation: true
        scaling: true
        perspective: true
        scaling_amplitude: 0.2
        perspective_amplitude_x: 0.2
        perspective_amplitude_y: 0.2
        allow_artifacts: true
        patch_ratio: 0.85
# Evaluation related config
evaluation:
    repeatability:
        # Initial random seed used to sample homographic augmentation
        seed: 200
        # Parameter used to sample illumination change evaluation set.
        photometric:
            enable: False
        # Parameter used to sample viewpoint change evaluation set.
        homographic:
            enable: True
            num_samples: 2
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57
                allow_artifacts: true
            valid_border_margin: 3